# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('emp_pic', models.ImageField(default='photo/no-img.jpg', upload_to='photo/')),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
