# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='basic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='da',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='esi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='hra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='pf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='ta',
            field=models.IntegerField(default=0),
        ),
    ]
